# Generated by Django 4.2.7 on 2025-08-22 02:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='ProcessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_processes', models.IntegerField(default=0)),
                ('total_cpu_percent', models.FloatField(default=0.0)),
                ('total_memory_mb', models.FloatField(default=0.0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.host')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('memory_mb', models.FloatField(default=0.0)),
                ('parent_pid', models.IntegerField(blank=True, null=True)),
                ('command_line', models.TextField(blank=True)),
                ('status', models.CharField(default='running', max_length=50)),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='api.processsnapshot')),
            ],
            options={
                'ordering': ['pid'],
            },
        ),
        migrations.AddIndex(
            model_name='processsnapshot',
            index=models.Index(fields=['host', '-timestamp'], name='api_process_host_id_8c5152_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['snapshot', 'pid'], name='api_process_snapsho_b7a746_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['snapshot', 'parent_pid'], name='api_process_snapsho_f95121_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('snapshot', 'pid')},
        ),
    ]
